[package]
name = "glorp"
description = "glorp for all you gleeby deebies... 👽"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

repository = "https://github.com/periaate/glorp"
homepage = "https://github.com/periaate/glorp"

[dependencies]
